/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jboss_summit2015_beacon_bluez_HCIDump */

#ifndef _Included_org_jboss_summit2015_beacon_bluez_HCIDump
#define _Included_org_jboss_summit2015_beacon_bluez_HCIDump
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jboss_summit2015_beacon_bluez_HCIDump_beacon_info_SIZEOF
#define org_jboss_summit2015_beacon_bluez_HCIDump_beacon_info_SIZEOF 80L
#undef org_jboss_summit2015_beacon_bluez_HCIDump_UUID_OFFSET
#define org_jboss_summit2015_beacon_bluez_HCIDump_UUID_OFFSET 0L
#undef org_jboss_summit2015_beacon_bluez_HCIDump_IS_HEARTBEAT_OFFSET
#define org_jboss_summit2015_beacon_bluez_HCIDump_IS_HEARTBEAT_OFFSET 36L
#undef org_jboss_summit2015_beacon_bluez_HCIDump_count_OFFSET
#define org_jboss_summit2015_beacon_bluez_HCIDump_count_OFFSET 40L
#undef org_jboss_summit2015_beacon_bluez_HCIDump_code_OFFSET
#define org_jboss_summit2015_beacon_bluez_HCIDump_code_OFFSET 44L
#undef org_jboss_summit2015_beacon_bluez_HCIDump_manufacturer_OFFSET
#define org_jboss_summit2015_beacon_bluez_HCIDump_manufacturer_OFFSET 48L
#undef org_jboss_summit2015_beacon_bluez_HCIDump_major_OFFSET
#define org_jboss_summit2015_beacon_bluez_HCIDump_major_OFFSET 52L
#undef org_jboss_summit2015_beacon_bluez_HCIDump_minor_OFFSET
#define org_jboss_summit2015_beacon_bluez_HCIDump_minor_OFFSET 56L
#undef org_jboss_summit2015_beacon_bluez_HCIDump_power_OFFSET
#define org_jboss_summit2015_beacon_bluez_HCIDump_power_OFFSET 60L
#undef org_jboss_summit2015_beacon_bluez_HCIDump_calibrated_power_OFFSET
#define org_jboss_summit2015_beacon_bluez_HCIDump_calibrated_power_OFFSET 64L
#undef org_jboss_summit2015_beacon_bluez_HCIDump_rssi_OFFSET
#define org_jboss_summit2015_beacon_bluez_HCIDump_rssi_OFFSET 68L
#undef org_jboss_summit2015_beacon_bluez_HCIDump_time_OFFSET
#define org_jboss_summit2015_beacon_bluez_HCIDump_time_OFFSET 72L
/*
 * Class:     org_jboss_summit2015_beacon_bluez_HCIDump
 * Method:    allocScanner
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_jboss_summit2015_beacon_bluez_HCIDump_allocScanner
        (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_jboss_summit2015_beacon_bluez_HCIDump
 * Method:    freeScanner
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jboss_summit2015_beacon_bluez_HCIDump_freeScanner
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
